Public Structure StructureDatabase
    Public Structure Tables
        Const AdminPermission = "AdminPermission"
        Const APCCommand = "APCCommand"
        Const Customer = "Customer"
        Const CustomerLoan = "CustomerLoan"
        Const Deliver = "Deliver"
        Const Mail = "Mail"
        Const Message = "Message"
        Const OnlineDB = "OnlineDB"
        Const Product = "Product"
        Const Receive = "Receive"
        Const Repair = "Repair"
        Const RepairActivity = "RepairActivity"
        Const RepairAdvanced = "RepairAdvanced"
        Const RepairRemarks1 = "RepairRemarks1"
        Const RepairRemarks2 = "RepairRemarks2"
        Const ReRepair = "Return"
        Const Sale = "Sale"
        Const SalesRepair = "SalesRepair"
        Const Settlement = "Settlement"
        Const Stock = "Stock"
        Const StockSale = "StockSale"
        Const StockSupply = "StockSupply"
        Const Supplier = "Supplier"
        Const Supply = "Supply"
        Const Technician = "Technician"
        Const TechnicianCost = "TechnicianCost"
        Const TechnicianLoan = "TechnicianLoan"
        Const TechnicianSalary = "TechnicianSalary"
        Const Transaction = "Transaction"
        Const User = "User"
    End Structure
    Public Structure Stock
        Const Code = "SNo"
        Const Category = "SCategory"
        Const Name = "SName"
        Const ModelNo = "SModelNo"
        Const Location = "SLocation"
        Const Details = "SDetails"
        Const SalePrice = "SSalePrice"
        Const CostPrice = "SCostPrice"
        Const LowestPrice = "SLowestPrice"
        Const AvailableUnits = "SAvailableStocks"
        Const DamagedUnits = "SOutofStocks"
        Const ReorderPoint = "SMinStocks"
    End Structure


End Structure
