'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My

    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.4.0.0"),
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase

        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()), MySettings)

#Region "My.Settings Auto-Save Functionality"
#If _MYTYPE = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(sender As Global.System.Object, e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region

        Public Shared ReadOnly Property [Default]() As MySettings
            Get

#If _MYTYPE = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("")>
        Public Property DatabaseCNN() As String
            Get
                Return CType(Me("DatabaseCNN"), String)
            End Get
            Set
                Me("DatabaseCNN") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("False")>
        Public Property SendSettlementEmail() As Boolean
            Get
                Return CType(Me("SendSettlementEmail"), Boolean)
            End Get
            Set
                Me("SendSettlementEmail") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("False")>
        Public Property DeliveredEmailtoT() As Boolean
            Get
                Return CType(Me("DeliveredEmailtoT"), Boolean)
            End Get
            Set
                Me("DeliveredEmailtoT") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("")>
        Public Property LastwrongLoginTime() As String
            Get
                Return CType(Me("LastwrongLoginTime"), String)
            End Get
            Set
                Me("LastwrongLoginTime") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("0")>
        Public Property CountwrongLogins() As Integer
            Get
                Return CType(Me("CountwrongLogins"), Integer)
            End Get
            Set
                Me("CountwrongLogins") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("")>
        Public Property AdminEmail() As String
            Get
                Return CType(Me("AdminEmail"), String)
            End Get
            Set
                Me("AdminEmail") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("Gainscha GS-2406T")>
        Public Property StickerPrinterName() As String
            Get
                Return CType(Me("StickerPrinterName"), String)
            End Get
            Set
                Me("StickerPrinterName") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("Repair Label")>
        Public Property RepairStickerPrinterPaperName() As String
            Get
                Return CType(Me("RepairStickerPrinterPaperName"), String)
            End Get
            Set
                Me("RepairStickerPrinterPaperName") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("Zonerich AB-220K")>
        Public Property BillPrinterName() As String
            Get
                Return CType(Me("BillPrinterName"), String)
            End Get
            Set
                Me("BillPrinterName") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("297mm * User Defined")>
        Public Property BillPrinterPaperName() As String
            Get
                Return CType(Me("BillPrinterPaperName"), String)
            End Get
            Set
                Me("BillPrinterPaperName") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("Stock Label")>
        Public Property StockStickerPaperName() As String
            Get
                Return CType(Me("StockStickerPaperName"), String)
            End Get
            Set
                Me("StockStickerPaperName") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("False")>
        Public Property BarcodeScannerCOMMode() As Boolean
            Get
                Return CType(Me("BarcodeScannerCOMMode"), Boolean)
            End Get
            Set
                Me("BarcodeScannerCOMMode") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("")>
        Public Property BarcodeScannerCOMPort1() As String
            Get
                Return CType(Me("BarcodeScannerCOMPort1"), String)
            End Get
            Set
                Me("BarcodeScannerCOMPort1") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("9600")>
        Public Property BarcodeScannerBaudRate() As String
            Get
                Return CType(Me("BarcodeScannerBaudRate"), String)
            End Get
            Set
                Me("BarcodeScannerBaudRate") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("")>
        Public Property ConfigCNN() As String
            Get
                Return CType(Me("ConfigCNN"), String)
            End Get
            Set
                Me("ConfigCNN") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("YJ9R8NnRqK5tUziPQb+lgQ==")>
        Public Property DBPassword() As String
            Get
                Return CType(Me("DBPassword"), String)
            End Get
            Set
                Me("DBPassword") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("Microsoft.ACE.OLEDB.12.0")>
        Public Property DBProvider() As String
            Get
                Return CType(Me("DBProvider"), String)
            End Get
            Set
                Me("DBProvider") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("False")>
        Public Property DeveloperMode() As Boolean
            Get
                Return CType(Me("DeveloperMode"), Boolean)
            End Get
            Set
                Me("DeveloperMode") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("")>
        Public Property BGWorkerPath() As String
            Get
                Return CType(Me("BGWorkerPath"), String)
            End Get
            Set
                Me("BGWorkerPath") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("False")>
        Public Property CashDrawer() As Boolean
            Get
                Return CType(Me("CashDrawer"), Boolean)
            End Get
            Set
                Me("CashDrawer") = Value
            End Set
        End Property
    End Class
End Namespace

Namespace My

    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>
    Friend Module MySettingsProperty

        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>
        Friend ReadOnly Property Settings() As Global.LASER_System.My.MySettings
            Get
                Return Global.LASER_System.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
