name: 🏷️ Create LASER System Release 
on:
    push:
        branches:
            - "32"
            
permissions:
    contents: write

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Extract version from LASER System.vbproj
        id: laser_system_get_version
        shell: pwsh
        run: |
          cd "LASER System"
          [xml]$proj = Get-Content "LASER System.vbproj"
          $version = $proj.Project.PropertyGroup.Version
          if (-not $version) { $version = $proj.Project.PropertyGroup.AssemblyVersion }
          if (-not $version) { $version = $proj.Project.PropertyGroup.FileVersion }
          echo "version=$version" | Out-File -FilePath $env:GITHUB_ENV -Append

      - name: Show version
        run: echo "Version is ${{ env.version }}"
