name: 🏷️ Create LASER System Release 
on:
    push:
        branches:
            - "32"
            
permissions:
    contents: write

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Extract version from LASER System.vbproj
        id: laser_system_get_version
        shell: pwsh
        run: |
          cd "LASER System"
          [xml]$proj = Get-Content "LASER System.vbproj"
          $appVersion = $proj.Project.PropertyGroup.ApplicationVersion
          $revision   = $proj.Project.PropertyGroup.ApplicationRevision

          # Replace * or %2a with the revision number
          $version = $appVersion -replace '\*|%2a', $revision

          echo "version=$version" | Out-File -FilePath $env:GITHUB_ENV -Append

      - name: Show version
        run: echo "Version is ${{ env.version }}"
