name: Publish LASER Cashier

on:
  push:
    branches: [ "32" ]
  pull_request:
    branches: [ "32" ]

jobs:

  build:
  
    runs-on: windows-latest 

    env:
      Solution_Name: "LASER System.sln"
      Folder_Name: LASER Cashier                       
      Branch: development
      
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Crystal Report
        run: |
          mkdir ./Crystal Report 
          cd ./Crystal Report
          curl https://origin-az.softwaredownloads.sap.com/public/file/0020000000674472023 -O ./Setup.exe
          msiexec /package CR13SP34MSI64_0-80007712.msi upgrade=1 /qn

    # # Add  MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
    # - name: Setup MSBuild.exe
    #   uses: microsoft/setup-msbuild@v1.0.2

    # - name: Setup Nuget
    #   uses: nuget/setup-nuget@v1
    #   with: 
    #     nuget-version: latest 

    # # Restore the Nuget packages
    # - name: Restore NuGet Packages
    #   run: nuget restore

    # - name: Build LASER Cashier Project
    #   run: cd ./LASER Cashier & msbuild 

    # - name: Publish LASER Cashier Project
    #   run: msbuild /t:publish /p:PublishDir="publish/" /property:UpdateEnabled=true /property:UpdateUrl="https://raw.githubusercontent.com/MaleeshaRodrigo/LASERSystem/${{env.Branch}}/LASER%20Cashier/publish/"
            

    
    
