name: Publish LASER System- Production

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:  
    runs-on: windows-latest 
    environment: development
    env:                    
      VERSION: 2.0.3.10
      BRANCH: main
      USER_NAME: MaleeshaRodrigo
      EMAIL: w1902272@my.westminster.ac.uk
      
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Push to development        
        run: echo "${{ secrets.KEY }}" 
