name: Publish LASER System- Development

on:
  push: 
    branches: [ "development" ]    
  pull_request:
    branches: [ "development" ]

jobs:
  build:  
    runs-on: windows-latest 
    env:                    
      VERSION: 2.0.3.10
      USER_NAME: MaleeshaRodrigo
      EMAIL: w1902272@my.westminster.ac.uk
      
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Chocolatey 
        uses: crazy-max/ghaction-chocolatey@v3
        with:
          args: -h
        
      - name: Install Crystal Report
        run: choco install crystalreports-for-visualstudio
        
      - name: Setup MSBuild.exe
        uses: microsoft/setup-msbuild@v1.0.2
  
      - name: Setup Nuget
        uses: nuget/setup-nuget@v1
        with: 
          nuget-version: latest 
  
      - name: Restore NuGet Packages
        run: nuget restore
  
      - name: Build LASER System Project      
        working-directory: "./LASER System"
        run: msbuild 
  
      - name: Publish LASER System Project
        working-directory: "./LASER System"
        run: msbuild /t:publish /p:PublishDir="publish/" /property:UpdateEnabled=true /property:UpdateUrl="https://raw.githubusercontent.com/MaleeshaRodrigo/LASERSystem/main/LASER%20System/publish/"  /p:configuration="Release" /p:ApplicationVersion=${{env.VERSION}}

      - name: Commit the changes
        run: |
          git config --global user.email "${{env.EMAIL}}"
          git config --global user.name "${{env.USER_NAME}}"
          git checkout -b feature-branch
          git add . 
          git commit -m "v${{env.VERSION}} published"

      - name: Push the changes
        run: git push

      - name: Create Pull Request
        uses: actions/github-script@v7.0.1
        with:
          script: |
            const newPR = await github.pulls.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: 'New Feature Pull Request',
              head: 'feature-branch',
              base: 'development', // Replace with your protected branch name
              body: 'Description of the changes.',
            });
  
      - name: Merge Pull Request
        uses: actions/github-script@v7.0.1
        with:
          script: |
            await github.pulls.merge({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: newPR.data.number,
            });
