name: Publish LASER System- Development

on:
  push:
    branches: [ "development" ]
  pull_request:
    branches: [ "development" ]

jobs:
  build:  
    runs-on: windows-latest 
    environment: development
    env:                    
      VERSION: 2.0.3.10
      BRANCH: development
      USER_NAME: MaleeshaRodrigo
      EMAIL: w1902272@my.westminster.ac.uk
      
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check secrets
        run: echo "${{ secrets.KEY }}"

